export const EventType = {

    //创建角色列表的part选择背景
    CHANGE_ROLE_PART_SELECT: 'CHANGE_ROLE_PART_SELECT',

    SEND_CAT_ACTION: "SEND_CAT_ACTION", //猫咪动作的事件
    SEND_BUY_SHOP_ITEM_SUCCESS_INFO: "SEND_BUY_SHOP_ITEM_INFO", //购买成功后的消息

    LOGIN_COMPELETED: "LOGIN_COMPELETED",


    PLAYER_KUANG_SELECT: "PLAYER_KUANG_SELECT",
    UPDTAE_PLAYER_KUANG: "UPDTAE_PLAYER_INFO",//更换刷新头像框

    UPDATE_ROLE_PLAY_INDEX: "UPDATE_ROLE_PLAY_INDEX", //更换人物部分的icon数组

    //显示对话记录按钮
    SHOW_CHAT_LOG_BUTTON: "UPDATE_GUIDE_INFO_WORK_PAGE",

    //显示打工按钮
    SHOW_WORK_BUTTON: "SHOW_WORK_BUTTON",

    //更新打工页引导信息
    UPDATE_GUIDE_INFO_WORK_PAGE: "UPDATE_GUIDE_INFO_WORK_PAGE",

    //更新首页引导信息
    UPDATE_GUIDE_INFO_MAIN_VIEW: "UPDATE_GUIDE_INFO_MAIN_VIEW",

    //更新好感度
    UPDATE_CAT_CV: "UPDATE_CAT_CV",

    //开始打工
    START_CAT_WORK: "START_CAT_WORK",

    //打工结果
    WORK_STATE_INFO: "WORK_STATE_INFO",

    //打工失败
    WORK_DEFAULT: "WORK_DEFAULT",

    FRESH_GAMELOCKED: "FRESH_GAMELOCKED",//锁定游戏
    FRESH_RENWU_REGE: "FRESH_RENWU_REGE",

    FRESH_CHUANDI_ZS: "FRESH_CHUANDI_ZS",

    //=============socket===============
    SOCKET_ONOPEN: "SOCKET_ONOPEN",
    SOCKET_ONMESSAGE: "SOCKET_ONMESSAGE",
    SOCKET_ONCLOSE: "SOCKET_ONCLOSE",
    SOCKET_ONERROR: "SOCKET_ONERROR",

    SOCKET_GETALL_NPCS: "SOCKET_GETALL_NPCS",//查询所有NPC
    SOCKET_ONLINE_NPCS: "SOCKET_ONLINE_NPCS",//上线NPC
    SOCKET_OFFLINE_NPCS: "SOCKET_OFFLINE_NPCS",//下线NPC

    SOCKET_NPC_MOVE: "SOCKET_NPC_MOVE",//下线NPC

    SOCKET_NPC_ACTION: "SOCKET_NPC_ACTION",//NPC action

    OBJECT_STATE_CHANGE: "OBJECT_STATE_CHANGE",//NPC action

    SOCKET_ITEM_STATE_CHANGE: "SOCKET_ITEM_STATE_CHANGE",//NPC action

    SOCKET_SELECT_CATS: "SOCKET_SELECT_CATS",
    SOCKET_CHANGE_CATS: "SOCKET_CHANGE_CATS",
    SOCKET_CHANGEINFO_CATS: "SOCKET_CHANGEINFO_CATS10004",
    SOCKET_CHECK_PLAYERITEMS: "SOCKET_CHECK_PLAYERITEMS",
    SOCKET_CHAT: "SOCKET_CHAT",
    SOCKET_CHATLIST: "SOCKET_CHATLIST",
    SOCKET_TASKLIST: "SOCKET_TASKLIST",
    SOCKET_TASK_CHANGE: "SOCKET_TASK_CHANGE",
    SOCKET_TASK_GET: "SOCKET_TASK_GET",
    SOCKET_SHARE: "SOCKET_SHARE",
    SOCKET_QIANDAO: "SOCKET_QISNANDAO",
    SOCKET_ITEMUPDATE: "SOCKET_ITEMUPDATE_10009",
    SOCKET_CHANGE_CATSDATA: "SOCKET_CHANGE_CATSDATA",
    SOCKET_ZHAOHU: "SOCKET_ZHAOHU",
    //=============shop=========================
    SOCKET_MOVE: "SOCKET_MOVE",
    //玩具列表
    SOCKET_TOY_LIST: "SOCKET_TOY_LIST",

    //==================ZHANG YIN========================
    //拉取聊天信息全量
    GETCHAT_BYID: "GETCHAT_BYID",
    //更新聊天信息
    UPDATE_CHAT: "UPDATE_CHAT",
    //更新物品信息
    UPDATE_ITEM: "UPDATE_ITEM",
    //通知场景动作
    SCENE_ACTION: "SCENE_ACTION",

    //通知UI界面初始化npcDirPrefab组件
    INIT_DIR_PREFAB: "INIT_DIR_PREFAB",

    //传送到目标npc位置
    TRANSPORT: "TRANSPORT",

    //启动NPC追随功能
    FOLLOWNPC: "FOLLOWNPC",

    //断线重连
    RELOGIN: "RELOGIN",

    //获取NPC聊天记录
    GETCHATRECORD: "GETCHATRECORD",

    //玩家创建角色成功
    CREATEPLAYER: "CREATEPLAYER",

    //销毁玩家创建角色
    DESTROYPLAYER: "DESTROYPLAYER",

    //销毁玩家创建角色
    PLAYERCLICK: "PLAYERCLICK",
    //销毁玩家创建角色
    DESTROYGUIDE: "DESTROYGUIDE",
    //获取所有NFT交互物品状态
    GETALLNFTSTATUS: "GETALLNFTSTATUS",
    //单个NFT状态产生变化
    CHANGENFTSTATUS: "CHANGENFTSTATUS",
    //NPC皮肤变更
    CHANGESKIN: "CHANGESKIN",

    //获取大厅信息
    GETLOBBYINFO: "GETLOBBYINFO",

    //请求进入房间
    REQUESTENTERSCENE: "REQUESTENTERSCENE",

    //请求进入房间
    RECONECTSCENE: "RECONECTSCENE",

    //场景家具变更
    CHANGESCENEITEM: "CHANGESCENEITEM",

    //弹出家具请求变更弹窗
    POPCHANGEITEM: "POPCHANGEITEM",

    //弹出家具请求变更弹窗
    CLOSEPOPCHANGE: "CLOSEPOPCHANGE",

    //弹出换装请求变更弹窗
    POPCHANGESKIN: "POPCHANGESKIN",
    //初始化twitter按钮
    INITTWITTERVIEW: "INITTWITTERVIEW",
    //更新TWITTER信息
    UPDATETWITTER: "UPDATETWITTER",
    //更新TWITTER内的评论的评论
    UPDATEREPLYITEM: "UPDATEREPLYITEM",
    //初始化拉取聊天记录
    INITCHATRECORD: "INITCHATRECORD",
    //初始化拉取聊天记录
    CHOOSENPCHEAD: "CHOOSENPCHEAD",
    //发送子弹消息
    SENDBULLETMSG: "SENDBULLETMSG",
    //初始化投票信息
    INITVOTEINFO: "INITVOTEINFO",
    //更新投票信息
    UPDATEVOTEINFO: "UPDATEVOTEINFO",
    //更新我的投票信息
    UPDATEMYVOTEINFO: "UPDATEMYVOTEINFO",
    //初始化故事信息
    INITSTORYINFO: "INITSTORYINFO",
    //初始化表情信息
    GEEMOJIINFO: "GEEMOJIINFO",
    //更新场景物品信息
    UPDATE_SCENE_ITEM: "UPDATE_SCENE_ITEM",
    //初始化新闻信息
    INITNEWSINFO: "INITNEWSINFO",
    PLAY_NEWS_VIDEO: "PLAY_VIDEO",
    PLAY_LOBBY_VIDEO: "PLAY_LOBBY_VIDEO",
    SWITCH_GAME_TWITTER_VIEW: "SWITCH_GAME_TWITTER_VIEW",
    GAME_TWITTER_VIEW_CHANGE_EP: "GAME_TWITTER_VIEW_CHANGE_EP",
    GAME_SWITCH_BANNER_NODE: "GAME_SWITCH_BANNER_NODE",

    // 拉取地图信息
    MAP_DATA: "MAP_DATA",
    // 
    SAVE_MAP: "SAVE_MAP",
    SAVE_NPC_DATA: "SAVE_NPC_DATA",
    // ai推送消息
    AI_MESSAGE: "AI_MESSAGE",
    // 
    INIT_AI_IMAGE: "INIT_AI_IMAGE",
    // 
    SWITCH_GAME_AI_IAMGE: "SWITCH_GAME_AI_IAMGE",
    // 获取剧场信息
    GETDRAMAINFO: "GETDRAMAINFO",
    // 
    NEWDRAMA: "NEWDRAMA"
}